// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PinatBot.Data;

#nullable disable

namespace PinatBot.Data.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20231216182833_AutoVoiceChannels")]
    partial class AutoVoiceChannels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PinatBot.Data.Modules.AutoVoiceChannels.AutoVoiceChannel", b =>
                {
                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("channel_id");

                    b.HasKey("ChannelId")
                        .HasName("pk_auto_voice_channels");

                    b.HasIndex("ChannelId")
                        .IsUnique()
                        .HasDatabaseName("ix_auto_voice_channels_channel_id");

                    b.ToTable("auto_voice_channels", (string)null);
                });

            modelBuilder.Entity("PinatBot.Data.Modules.AutoVoiceChannels.NewSessionChannel", b =>
                {
                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("channel_id");

                    b.Property<string>("ChildName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("child_name");

                    b.HasKey("ChannelId")
                        .HasName("pk_new_session_channels");

                    b.HasIndex("ChannelId")
                        .IsUnique()
                        .HasDatabaseName("ix_new_session_channels_channel_id");

                    b.ToTable("new_session_channels", (string)null);
                });

            modelBuilder.Entity("PinatBot.Data.Modules.Moderation.GeneralLoggingConfig", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("channel_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.HasKey("GuildId")
                        .HasName("pk_general_logging_configs");

                    b.HasIndex("GuildId")
                        .IsUnique()
                        .HasDatabaseName("ix_general_logging_configs_guild_id");

                    b.ToTable("general_logging_configs", (string)null);
                });

            modelBuilder.Entity("PinatBot.Data.Modules.Moderation.MemberJoinRoleConfig", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("role_id");

                    b.HasKey("GuildId")
                        .HasName("pk_member_join_role_configs");

                    b.HasIndex("GuildId")
                        .IsUnique()
                        .HasDatabaseName("ix_member_join_role_configs_guild_id");

                    b.ToTable("member_join_role_configs", (string)null);
                });

            modelBuilder.Entity("PinatBot.Data.Modules.Moderation.VoiceStateLoggingConfig", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("channel_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.HasKey("GuildId")
                        .HasName("pk_voice_state_logging_configs");

                    b.HasIndex("GuildId")
                        .IsUnique()
                        .HasDatabaseName("ix_voice_state_logging_configs_guild_id");

                    b.ToTable("voice_state_logging_configs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
